host: 0.0.0.0
port: 25565
motd: "<rainbow>Default loadbalancer config"
connectionError: "<red>Could not connect you to backend server.</red>"
static:
  enabled: true
  targets:
    - address: localhost
      port: 25566
    - address: localhost
      port: 25567
http:
  enabled: false
  host: https://example.com/{username}/{uuid}
  hostPath: "$.host"
  portPath: "$.port"
geo:
  enabled: true
  token: ''
  fallback:
    address: localhost
    port: 25567
  filters:
    - type: country
      value: US
      targets:
        - address: localhost
          port: 25568
    - type: country
      value: DE
      targets:
        - address: localhost
          port: 25569